notifications/urls.py
''' Django notification urls file '''
# -*- coding: utf-8 -*-
from distutils.version import StrictVersion  # pylint: disable=no-name-in-module,import-error

from django import get_version

from . import views

if StrictVersion(get_version()) >= StrictVersion('2.0'):
    from django.urls import re_path as pattern
else:
    from django.conf.urls import url as pattern


urlpatterns = [
    pattern(r'^$', views.AllNotificationsList.as_view(), name='all'),
    pattern(r'^unread/$', views.UnreadNotificationsList.as_view(), name='unread'),
    pattern(r'^mark-all-as-read/$', views.mark_all_as_read, name='mark_all_as_read'),
    pattern(r'^mark-as-read/(?P<slug>\d+)/$', views.mark_as_read, name='mark_as_read'),
    pattern(r'^mark-as-unread/(?P<slug>\d+)/$', views.mark_as_unread, name='mark_as_unread'),
    pattern(r'^delete/(?P<slug>\d+)/$', views.delete, name='delete'),
    pattern(r'^api/unread_count/$', views.live_unread_notification_count, name='live_unread_notification_count'),
    pattern(r'^api/all_count/$', views.live_all_notification_count, name='live_all_notification_count'),
    pattern(r'^api/unread_list/$', views.live_unread_notification_list, name='live_unread_notification_list'),
    pattern(r'^api/all_list/', views.live_all_notification_list, name='live_all_notification_list'),
]

app_name = 'notifications'

notifications/models.py
from swapper import swappable_setting

from .base.models import AbstractNotification, notify_handler  # noqa


class Notification(AbstractNotification):

    class Meta(AbstractNotification.Meta):
        abstract = False
        swappable = swappable_setting('notifications', 'Notification')

notifications/views.py
# -*- coding: utf-8 -*-
''' Django Notifications example views '''
from distutils.version import StrictVersion  # pylint: disable=no-name-in-module,import-error

from django import get_version
from django.contrib.auth.decorators import login_required
from django.forms import model_to_dict
from django.shortcuts import get_object_or_404, redirect
from django.utils.decorators import method_decorator
from django.views.generic import ListView
from notifications import settings
from notifications.models import Notification
from notifications.utils import id2slug, slug2id
from notifications.settings import get_config
from django.views.decorators.cache import never_cache

if StrictVersion(get_version()) >= StrictVersion('1.7.0'):
    from django.http import JsonResponse  # noqa
else:
    # Django 1.6 doesn't have a proper JsonResponse
    import json
    from django.http import HttpResponse  # noqa

    def date_handler(obj):
        return obj.isoformat() if hasattr(obj, 'isoformat') else obj

    def JsonResponse(data):  # noqa
        return HttpResponse(
            json.dumps(data, default=date_handler),
            content_type="application/json")


class NotificationViewList(ListView):
    template_name = 'notifications/list.html'
    context_object_name = 'notifications'
    paginate_by = settings.get_config()['PAGINATE_BY']

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(NotificationViewList, self).dispatch(
            request, *args, **kwargs)


class AllNotificationsList(NotificationViewList):
    """
    Index page for authenticated user
    """

    def get_queryset(self):
        if settings.get_config()['SOFT_DELETE']:
            qset = self.request.user.notifications.active()
        else:
            qset = self.request.user.notifications.all()
        return qset


class UnreadNotificationsList(NotificationViewList):

    def get_queryset(self):
        return self.request.user.notifications.unread()


@login_required
def mark_all_as_read(request):
    request.user.notifications.mark_all_as_read()

    _next = request.GET.get('next')

    if _next:
        return redirect(_next)
    return redirect('notifications:unread')

@login_required
def mark_as_read(request, slug=None):
    notification_id = slug2id(slug)

    notification = get_object_or_404(
        Notification, recipient=request.user, id=notification_id)
    notification.mark_as_read()

    _next = request.GET.get('next')

    if _next:
        return redirect(_next)

    return redirect('notifications:unread')


@login_required
def mark_as_unread(request, slug=None):
    notification_id = slug2id(slug)

    notification = get_object_or_404(
        Notification, recipient=request.user, id=notification_id)
    notification.mark_as_unread()

    _next = request.GET.get('next')

    if _next:
        return redirect(_next)

    return redirect('notifications:unread')


@login_required
def delete(request, slug=None):
    notification_id = slug2id(slug)

    notification = get_object_or_404(
        Notification, recipient=request.user, id=notification_id)

    if settings.get_config()['SOFT_DELETE']:
        notification.deleted = True
        notification.save()
    else:
        notification.delete()

    _next = request.GET.get('next')

    if _next:
        return redirect(_next)

    return redirect('notifications:all')


@never_cache
def live_unread_notification_count(request):
    try:
        user_is_authenticated = request.user.is_authenticated()
    except TypeError:  # Django >= 1.11
        user_is_authenticated = request.user.is_authenticated

    if not user_is_authenticated:
        data = {
            'unread_count': 0
        }
    else:
        data = {
            'unread_count': request.user.notifications.unread().count(),
        }
    return JsonResponse(data)


@never_cache
def live_unread_notification_list(request):
    ''' Return a json with a unread notification list '''
    try:
        user_is_authenticated = request.user.is_authenticated()
    except TypeError:  # Django >= 1.11
        user_is_authenticated = request.user.is_authenticated

    if not user_is_authenticated:
        data = {
            'unread_count': 0,
            'unread_list': []
        }
        return JsonResponse(data)

    default_num_to_fetch = get_config()['NUM_TO_FETCH']
    try:
        # If they don't specify, make it 5.
        num_to_fetch = request.GET.get('max', default_num_to_fetch)
        num_to_fetch = int(num_to_fetch)
        if not (1 <= num_to_fetch <= 100):
            num_to_fetch = default_num_to_fetch
    except ValueError:  # If casting to an int fails.
        num_to_fetch = default_num_to_fetch

    unread_list = []

    for notification in request.user.notifications.unread()[0:num_to_fetch]:
        struct = model_to_dict(notification)
        struct['slug'] = id2slug(notification.id)
        if notification.actor:
            struct['actor'] = str(notification.actor)
        if notification.target:
            struct['target'] = str(notification.target)
        if notification.action_object:
            struct['action_object'] = str(notification.action_object)
        if notification.data:
            struct['data'] = notification.data
        unread_list.append(struct)
        if request.GET.get('mark_as_read'):
            notification.mark_as_read()
    data = {
        'unread_count': request.user.notifications.unread().count(),
        'unread_list': unread_list
    }
    return JsonResponse(data)


@never_cache
def live_all_notification_list(request):
    ''' Return a json with a unread notification list '''
    try:
        user_is_authenticated = request.user.is_authenticated()
    except TypeError:  # Django >= 1.11
        user_is_authenticated = request.user.is_authenticated

    if not user_is_authenticated:
        data = {
            'all_count': 0,
            'all_list': []
        }
        return JsonResponse(data)

    default_num_to_fetch = get_config()['NUM_TO_FETCH']
    try:
        # If they don't specify, make it 5.
        num_to_fetch = request.GET.get('max', default_num_to_fetch)
        num_to_fetch = int(num_to_fetch)
        if not (1 <= num_to_fetch <= 100):
            num_to_fetch = default_num_to_fetch
    except ValueError:  # If casting to an int fails.
        num_to_fetch = default_num_to_fetch

    all_list = []

    for notification in request.user.notifications.all()[0:num_to_fetch]:
        struct = model_to_dict(notification)
        struct['slug'] = id2slug(notification.id)
        if notification.actor:
            struct['actor'] = str(notification.actor)
        if notification.target:
            struct['target'] = str(notification.target)
        if notification.action_object:
            struct['action_object'] = str(notification.action_object)
        if notification.data:
            struct['data'] = notification.data
        all_list.append(struct)
        if request.GET.get('mark_as_read'):
            notification.mark_as_read()
    data = {
        'unread_count': request.user.notifications.unread().count(),
        'all_list': all_list
    }
    return JsonResponse(data)


def live_all_notification_count(request):
    try:
        user_is_authenticated = request.user.is_authenticated()
    except TypeError:  # Django >= 1.11
        user_is_authenticated = request.user.is_authenticated

    if not user_is_authenticated:
        data = {
            'all_count': 0
        }
    else:
        data = {
            'all_count': request.user.notifications.count(),
        }
    return JsonResponse(data)

notifications/templates/notifications/header_notifications.html
{% load static %}
{% load notifications_tags %}

<!-- Nav Item - Alerts -->
<li class="nav-item dropdown no-arrow mx-1">
    <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown"
       aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-bell fa-fw"></i>

        <span class="badge badge-danger badge-counter live_notify_badge"></span>
    </a>
    <!-- Dropdown - Alerts -->
    <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
         aria-labelledby="alertsDropdown">
        <h6 class="dropdown-header">
            Notifications
        </h6>
        <span class="live_notify_list">
        </span>
    </div>
</li>
<script src="{% static 'notifications/notify.js' %}" type="text/javascript"></script>
<script>
    function my_special_notification_callback(data) {
        $(".live_notify_list").empty();
        for (var i = 0; i < data.all_list.length; i++) {
            var notice = data.all_list[i];
            var notice_item = $('<a></a>');
            if (notice.unread)
                notice_item.attr("class", "dropdown-item d-flex align-items-center bg-dark");
            else
                notice_item.attr("class", "dropdown-item d-flex align-items-center bg-gray");

            notice_item.attr("href", notice.verb);
            notice_item.attr("onclick", 'markAsRead(' + notice.slug + ')');

            var notice_description = $('<p></p>');
            var notice_time = $('<span></span>');

            if (notice.unread) {
                notice_description.attr("class", "font-weight-bold text-white ");
                notice_time.attr("class", "font-weight-bold text-white ");
            }


            notice_description.text(notice.description);
            notice_time.text(humanized_time_span(notice.timestamp));

            var notice_content = $('<div></div>').append(notice_description);
            notice_content = notice_content.append(notice_time)
            notice_item.append(notice_content);
            $(".live_notify_list").append(notice_item);

        }
        if (data.all_list.length === 0) {
            $(".live_notify_list").text('no notification to show');
        }
    }

    function markAsRead(slug) {
        $.get('/notifications/mark-as-read/' + slug, function (data) {
        });
    }

    function humanized_time_span(date, ref_date, date_formats, time_units) {
        //Date Formats must be be ordered smallest -> largest and must end in a format with ceiling of null
        date_formats = date_formats || {
            past: [
                {ceiling: 60, text: "$seconds seconds ago"},
                {ceiling: 3600, text: "$minutes minutes ago"},
                {ceiling: 86400, text: "$hours hours ago"},
                {ceiling: 2629744, text: "$days days ago"},
                {ceiling: 31556926, text: "$months months ago"},
                {ceiling: null, text: "$years years ago"}
            ],
            future: [
                {ceiling: 60, text: "in $seconds seconds"},
                {ceiling: 3600, text: "in $minutes minutes"},
                {ceiling: 86400, text: "in $hours hours"},
                {ceiling: 2629744, text: "in $days days"},
                {ceiling: 31556926, text: "in $months months"},
                {ceiling: null, text: "in $years years"}
            ]
        };
        //Time units must be be ordered largest -> smallest
        time_units = time_units || [
            [31556926, 'years'],
            [2629744, 'months'],
            [86400, 'days'],
            [3600, 'hours'],
            [60, 'minutes'],
            [1, 'seconds']
        ];

        date = new Date(date);
        ref_date = ref_date ? new Date(ref_date) : new Date();
        var seconds_difference = (ref_date - date) / 1000;

        var tense = 'past';
        if (seconds_difference < 0) {
            tense = 'future';
            seconds_difference = 0 - seconds_difference;
        }

        function get_format() {
            for (var i = 0; i < date_formats[tense].length; i++) {
                if (date_formats[tense][i].ceiling == null || seconds_difference <= date_formats[tense][i].ceiling) {
                    return date_formats[tense][i];
                }
            }
            return null;
        }

        function get_time_breakdown() {
            var seconds = seconds_difference;
            var breakdown = {};
            for (var i = 0; i < time_units.length; i++) {
                var occurences_of_unit = Math.floor(seconds / time_units[i][0]);
                seconds = seconds - (time_units[i][0] * occurences_of_unit);
                breakdown[time_units[i][1]] = occurences_of_unit;
            }
            return breakdown;
        }

        function render_date(date_format) {
            var breakdown = get_time_breakdown();
            var time_ago_text = date_format.text.replace(/\$(\w+)/g, function () {
                return breakdown[arguments[1]];
            });
            return depluralize_time_ago_text(time_ago_text, breakdown);
        }

        function depluralize_time_ago_text(time_ago_text, breakdown) {
            for (var i in breakdown) {
                if (breakdown[i] == 1) {
                    var regexp = new RegExp("\\b" + i + "\\b");
                    time_ago_text = time_ago_text.replace(regexp, function () {
                        return arguments[0].replace(/s\b/g, '');
                    });
                }
            }
            return time_ago_text;
        }

        return render_date(get_format());
    }
</script>
{% register_notify_callbacks callbacks='fill_notification_badge,my_special_notification_callback' %}

notifications/templates/notifications/list.html
<ul class="notifications">
  {% for notice in notifications %}
    {% include 'notifications/notice.html' %}
  {% endfor %}
</ul>

notifications/templates/notifications/notice.html
<div class="alert alert-block alert-{{ notice.level }}">
  <a class="close pull-right" href="{% url 'notifications:mark_as_read' notice.slug %}">
    <i class="icon-close"></i>
  </a>
  
  <h4>
    <i class="icon-mail{% if notice.unread %}-alt{% endif %}"></i>
    {{ notice.actor }} 
    {{ notice.verb }}
    {% if notice.target %}
      of {{ notice.target }}
    {% endif %}
  </h4>
  
  <p>{{ notice.timesince }} ago</p>
  
  <p>{{ notice.description|linebreaksbr }}</p>
  
  <div class="notice-actions">
    {% for action in notice.data.actions %}
      <a class="btn" href="{{ action.href }}">{{ action.title }}</a>
    {% endfor %}
  </div>
</div>

notifications/templates/notifications/test_tags.html
{% load notifications_tags %}

{% register_notify_callbacks callbacks='fill_notification_menu,fill_notification_badge' %}

{% notifications_unread as unread %}
{{ unread }}
{% live_notify_badge %}
{% live_notify_list %}